language: node_js
node_js:
  - "7.9.0"

cache:
  directories:
    - node_modules
  yarn: true

os:
  - linux
  - osx

addons:
   apt:
     packages:
       - libsecret-1-dev
 
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - export CI=true
  - npm i -g vsce
  - npm install
  - npm run vscode:prepublish

script:
  - vsce package -o LiveSassCompiler-$TRAVIS_TAG-$TRAVIS_OS_NAME.vsix

deploy:
  provider: releases
  api_key: $github_token
  file: "*.vsix"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true